from pydantic import BaseModel, Field
from typing import List


class Source(BaseModel):
    """
    Represents a citation used in the response.
    """

    document: str = Field(
        ...,
        description="Source policy document name.",
        examples=[
            "01_Leave_and_Attendance_Policy.pdf",
        ],
    )

    page: int = Field(
        ...,
        ge=1,
        description="Page number in the source document.",
        examples=[5],
    )


class RetrievedChunk(BaseModel):
    """
    Represents a policy chunk retrieved from the vector database.
    """

    source: str = Field(
        ...,
        description="Source policy document.",
    )

    page: int = Field(
        ...,
        ge=1,
        description="Page number.",
    )

    chunk_id: str = Field(
        ...,
        description="Unique chunk identifier.",
    )

    similarity_score: float = Field(
        ...,
        ge=0,
        description="Similarity score.",
    )

    content: str = Field(
        ...,
        description="Retrieved chunk content.",
    )


class ChatResponse(BaseModel):
    """
    Response generated by the LLM.

    Only the answer should be generated by the model.
    Sources and tools are added by backend.
    """

    answer: str = Field(
        ...,
        description="Final answer generated by assistant.",
    )